apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: deepak-space # here ns is getting created
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deepakday3webapp
  name: deepakday3webapp
  namespace: deepak-space #namespace is used from above
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepakday3webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deepakday3webapp # real label of pod 
    spec: 
      containers:
      - image: dbadoni/microsoftapp:v003
        name: microsoftapp
        imagePullPolicy: Always
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deepakday3svc1
  name: deepakday3svc1
  namespace: deepak-space
spec:
  ports:
  - name: 1313-80
    port: 1313
    protocol: TCP
    targetPort: 80
  selector:
    app: deepakday3webapp # matching label of pods 
  type: NodePort
status:
  loadBalancer: {}
